// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ChatMessageHandle : RemoteTableHandle<EventContext, ChatMessage>
        {
            protected override string RemoteTableName => "chat_message";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(ChatMessage row) => row.Id;

                public IdUniqueIndex(ChatMessageHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal ChatMessageHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(ChatMessage row) => row.Id;
        }

        public readonly ChatMessageHandle ChatMessage;
    }

    public sealed class ChatMessageCols
    {
        public global::SpacetimeDB.Col<ChatMessage, ulong> Id { get; }
        public global::SpacetimeDB.Col<ChatMessage, SpacetimeDB.Identity> Sender { get; }
        public global::SpacetimeDB.Col<ChatMessage, string> SenderName { get; }
        public global::SpacetimeDB.Col<ChatMessage, string> Text { get; }
        public global::SpacetimeDB.Col<ChatMessage, SpacetimeDB.Timestamp> SentAt { get; }

        public ChatMessageCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<ChatMessage, ulong>(tableName, "id");
            Sender = new global::SpacetimeDB.Col<ChatMessage, SpacetimeDB.Identity>(tableName, "sender");
            SenderName = new global::SpacetimeDB.Col<ChatMessage, string>(tableName, "sender_name");
            Text = new global::SpacetimeDB.Col<ChatMessage, string>(tableName, "text");
            SentAt = new global::SpacetimeDB.Col<ChatMessage, SpacetimeDB.Timestamp>(tableName, "sent_at");
        }
    }

    public sealed class ChatMessageIxCols
    {
        public global::SpacetimeDB.IxCol<ChatMessage, ulong> Id { get; }

        public ChatMessageIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<ChatMessage, ulong>(tableName, "id");
        }
    }
}
