// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class DensityEditHandle : RemoteTableHandle<EventContext, DensityEdit>
        {
            protected override string RemoteTableName => "density_edit";

            public sealed class KeyUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(DensityEdit row) => row.Key;

                public KeyUniqueIndex(DensityEditHandle table) : base(table) { }
            }

            public readonly KeyUniqueIndex Key;

            public sealed class WorldIdIndex : BTreeIndexBase<string>
            {
                protected override string GetKey(DensityEdit row) => row.WorldId;

                public WorldIdIndex(DensityEditHandle table) : base(table) { }
            }

            public readonly WorldIdIndex WorldId;

            internal DensityEditHandle(DbConnection conn) : base(conn)
            {
                Key = new(this);
                WorldId = new(this);
            }

            protected override object GetPrimaryKey(DensityEdit row) => row.Key;
        }

        public readonly DensityEditHandle DensityEdit;
    }

    public sealed class DensityEditCols
    {
        public global::SpacetimeDB.Col<DensityEdit, string> Key { get; }
        public global::SpacetimeDB.Col<DensityEdit, string> WorldId { get; }
        public global::SpacetimeDB.Col<DensityEdit, int> X { get; }
        public global::SpacetimeDB.Col<DensityEdit, int> Y { get; }
        public global::SpacetimeDB.Col<DensityEdit, int> Z { get; }
        public global::SpacetimeDB.Col<DensityEdit, float> Density { get; }
        public global::SpacetimeDB.Col<DensityEdit, uint> Material { get; }
        public global::SpacetimeDB.Col<DensityEdit, SpacetimeDB.Identity> EditedBy { get; }
        public global::SpacetimeDB.Col<DensityEdit, SpacetimeDB.Timestamp> EditedAt { get; }

        public DensityEditCols(string tableName)
        {
            Key = new global::SpacetimeDB.Col<DensityEdit, string>(tableName, "key");
            WorldId = new global::SpacetimeDB.Col<DensityEdit, string>(tableName, "world_id");
            X = new global::SpacetimeDB.Col<DensityEdit, int>(tableName, "x");
            Y = new global::SpacetimeDB.Col<DensityEdit, int>(tableName, "y");
            Z = new global::SpacetimeDB.Col<DensityEdit, int>(tableName, "z");
            Density = new global::SpacetimeDB.Col<DensityEdit, float>(tableName, "density");
            Material = new global::SpacetimeDB.Col<DensityEdit, uint>(tableName, "material");
            EditedBy = new global::SpacetimeDB.Col<DensityEdit, SpacetimeDB.Identity>(tableName, "edited_by");
            EditedAt = new global::SpacetimeDB.Col<DensityEdit, SpacetimeDB.Timestamp>(tableName, "edited_at");
        }
    }

    public sealed class DensityEditIxCols
    {
        public global::SpacetimeDB.IxCol<DensityEdit, string> Key { get; }
        public global::SpacetimeDB.IxCol<DensityEdit, string> WorldId { get; }

        public DensityEditIxCols(string tableName)
        {
            Key = new global::SpacetimeDB.IxCol<DensityEdit, string>(tableName, "key");
            WorldId = new global::SpacetimeDB.IxCol<DensityEdit, string>(tableName, "world_id");
        }
    }
}
