// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlayerHandle : RemoteTableHandle<EventContext, Player>
        {
            protected override string RemoteTableName => "player";

            public sealed class IdentityUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(Player row) => row.Identity;

                public IdentityUniqueIndex(PlayerHandle table) : base(table) { }
            }

            public readonly IdentityUniqueIndex Identity;

            internal PlayerHandle(DbConnection conn) : base(conn)
            {
                Identity = new(this);
            }

            protected override object GetPrimaryKey(Player row) => row.Identity;
        }

        public readonly PlayerHandle Player;
    }

    public sealed class PlayerCols
    {
        public global::SpacetimeDB.Col<Player, SpacetimeDB.Identity> Identity { get; }
        public global::SpacetimeDB.Col<Player, string> Name { get; }
        public global::SpacetimeDB.Col<Player, bool> Online { get; }
        public global::SpacetimeDB.Col<Player, float> X { get; }
        public global::SpacetimeDB.Col<Player, float> Y { get; }
        public global::SpacetimeDB.Col<Player, float> Z { get; }
        public global::SpacetimeDB.Col<Player, float> Yaw { get; }
        public global::SpacetimeDB.Col<Player, float> Pitch { get; }
        public global::SpacetimeDB.Col<Player, uint> ColorRgba { get; }
        public global::SpacetimeDB.Col<Player, SpacetimeDB.Timestamp> LastSeen { get; }

        public PlayerCols(string tableName)
        {
            Identity = new global::SpacetimeDB.Col<Player, SpacetimeDB.Identity>(tableName, "identity");
            Name = new global::SpacetimeDB.Col<Player, string>(tableName, "name");
            Online = new global::SpacetimeDB.Col<Player, bool>(tableName, "online");
            X = new global::SpacetimeDB.Col<Player, float>(tableName, "x");
            Y = new global::SpacetimeDB.Col<Player, float>(tableName, "y");
            Z = new global::SpacetimeDB.Col<Player, float>(tableName, "z");
            Yaw = new global::SpacetimeDB.Col<Player, float>(tableName, "yaw");
            Pitch = new global::SpacetimeDB.Col<Player, float>(tableName, "pitch");
            ColorRgba = new global::SpacetimeDB.Col<Player, uint>(tableName, "color_rgba");
            LastSeen = new global::SpacetimeDB.Col<Player, SpacetimeDB.Timestamp>(tableName, "last_seen");
        }
    }

    public sealed class PlayerIxCols
    {
        public global::SpacetimeDB.IxCol<Player, SpacetimeDB.Identity> Identity { get; }

        public PlayerIxCols(string tableName)
        {
            Identity = new global::SpacetimeDB.IxCol<Player, SpacetimeDB.Identity>(tableName, "identity");
        }
    }
}
