// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class VoxelEditHandle : RemoteTableHandle<EventContext, VoxelEdit>
        {
            protected override string RemoteTableName => "voxel_edit";

            public sealed class KeyUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(VoxelEdit row) => row.Key;

                public KeyUniqueIndex(VoxelEditHandle table) : base(table) { }
            }

            public readonly KeyUniqueIndex Key;

            public sealed class WorldIdIndex : BTreeIndexBase<string>
            {
                protected override string GetKey(VoxelEdit row) => row.WorldId;

                public WorldIdIndex(VoxelEditHandle table) : base(table) { }
            }

            public readonly WorldIdIndex WorldId;

            internal VoxelEditHandle(DbConnection conn) : base(conn)
            {
                Key = new(this);
                WorldId = new(this);
            }

            protected override object GetPrimaryKey(VoxelEdit row) => row.Key;
        }

        public readonly VoxelEditHandle VoxelEdit;
    }

    public sealed class VoxelEditCols
    {
        public global::SpacetimeDB.Col<VoxelEdit, string> Key { get; }
        public global::SpacetimeDB.Col<VoxelEdit, string> WorldId { get; }
        public global::SpacetimeDB.Col<VoxelEdit, int> X { get; }
        public global::SpacetimeDB.Col<VoxelEdit, int> Y { get; }
        public global::SpacetimeDB.Col<VoxelEdit, int> Z { get; }
        public global::SpacetimeDB.Col<VoxelEdit, uint> Material { get; }
        public global::SpacetimeDB.Col<VoxelEdit, SpacetimeDB.Identity> EditedBy { get; }
        public global::SpacetimeDB.Col<VoxelEdit, SpacetimeDB.Timestamp> EditedAt { get; }

        public VoxelEditCols(string tableName)
        {
            Key = new global::SpacetimeDB.Col<VoxelEdit, string>(tableName, "key");
            WorldId = new global::SpacetimeDB.Col<VoxelEdit, string>(tableName, "world_id");
            X = new global::SpacetimeDB.Col<VoxelEdit, int>(tableName, "x");
            Y = new global::SpacetimeDB.Col<VoxelEdit, int>(tableName, "y");
            Z = new global::SpacetimeDB.Col<VoxelEdit, int>(tableName, "z");
            Material = new global::SpacetimeDB.Col<VoxelEdit, uint>(tableName, "material");
            EditedBy = new global::SpacetimeDB.Col<VoxelEdit, SpacetimeDB.Identity>(tableName, "edited_by");
            EditedAt = new global::SpacetimeDB.Col<VoxelEdit, SpacetimeDB.Timestamp>(tableName, "edited_at");
        }
    }

    public sealed class VoxelEditIxCols
    {
        public global::SpacetimeDB.IxCol<VoxelEdit, string> Key { get; }
        public global::SpacetimeDB.IxCol<VoxelEdit, string> WorldId { get; }

        public VoxelEditIxCols(string tableName)
        {
            Key = new global::SpacetimeDB.IxCol<VoxelEdit, string>(tableName, "key");
            WorldId = new global::SpacetimeDB.IxCol<VoxelEdit, string>(tableName, "world_id");
        }
    }
}
