// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class WorldStateHandle : RemoteTableHandle<EventContext, WorldState>
        {
            protected override string RemoteTableName => "world_state";

            public sealed class WorldIdUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(WorldState row) => row.WorldId;

                public WorldIdUniqueIndex(WorldStateHandle table) : base(table) { }
            }

            public readonly WorldIdUniqueIndex WorldId;

            internal WorldStateHandle(DbConnection conn) : base(conn)
            {
                WorldId = new(this);
            }

            protected override object GetPrimaryKey(WorldState row) => row.WorldId;
        }

        public readonly WorldStateHandle WorldState;
    }

    public sealed class WorldStateCols
    {
        public global::SpacetimeDB.Col<WorldState, string> WorldId { get; }
        public global::SpacetimeDB.Col<WorldState, int> WorldSeed { get; }
        public global::SpacetimeDB.Col<WorldState, uint> GeneratorVersion { get; }
        public global::SpacetimeDB.Col<WorldState, byte> TerrainSystem { get; }
        public global::SpacetimeDB.Col<WorldState, float> VoxelSize { get; }
        public global::SpacetimeDB.Col<WorldState, int> MinChunkY { get; }
        public global::SpacetimeDB.Col<WorldState, int> MaxChunkY { get; }
        public global::SpacetimeDB.Col<WorldState, int> WorldMinChunkX { get; }
        public global::SpacetimeDB.Col<WorldState, int> WorldMinChunkZ { get; }
        public global::SpacetimeDB.Col<WorldState, int> WorldMaxChunkX { get; }
        public global::SpacetimeDB.Col<WorldState, int> WorldMaxChunkZ { get; }
        public global::SpacetimeDB.Col<WorldState, string> GenerationProfileId { get; }
        public global::SpacetimeDB.Col<WorldState, string> GenerationSignature { get; }
        public global::SpacetimeDB.Col<WorldState, SpacetimeDB.Identity> UpdatedBy { get; }
        public global::SpacetimeDB.Col<WorldState, SpacetimeDB.Timestamp> UpdatedAt { get; }

        public WorldStateCols(string tableName)
        {
            WorldId = new global::SpacetimeDB.Col<WorldState, string>(tableName, "world_id");
            WorldSeed = new global::SpacetimeDB.Col<WorldState, int>(tableName, "world_seed");
            GeneratorVersion = new global::SpacetimeDB.Col<WorldState, uint>(tableName, "generator_version");
            TerrainSystem = new global::SpacetimeDB.Col<WorldState, byte>(tableName, "terrain_system");
            VoxelSize = new global::SpacetimeDB.Col<WorldState, float>(tableName, "voxel_size");
            MinChunkY = new global::SpacetimeDB.Col<WorldState, int>(tableName, "min_chunk_y");
            MaxChunkY = new global::SpacetimeDB.Col<WorldState, int>(tableName, "max_chunk_y");
            WorldMinChunkX = new global::SpacetimeDB.Col<WorldState, int>(tableName, "world_min_chunk_x");
            WorldMinChunkZ = new global::SpacetimeDB.Col<WorldState, int>(tableName, "world_min_chunk_z");
            WorldMaxChunkX = new global::SpacetimeDB.Col<WorldState, int>(tableName, "world_max_chunk_x");
            WorldMaxChunkZ = new global::SpacetimeDB.Col<WorldState, int>(tableName, "world_max_chunk_z");
            GenerationProfileId = new global::SpacetimeDB.Col<WorldState, string>(tableName, "generation_profile_id");
            GenerationSignature = new global::SpacetimeDB.Col<WorldState, string>(tableName, "generation_signature");
            UpdatedBy = new global::SpacetimeDB.Col<WorldState, SpacetimeDB.Identity>(tableName, "updated_by");
            UpdatedAt = new global::SpacetimeDB.Col<WorldState, SpacetimeDB.Timestamp>(tableName, "updated_at");
        }
    }

    public sealed class WorldStateIxCols
    {
        public global::SpacetimeDB.IxCol<WorldState, string> WorldId { get; }

        public WorldStateIxCols(string tableName)
        {
            WorldId = new global::SpacetimeDB.IxCol<WorldState, string>(tableName, "world_id");
        }
    }
}
