// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class WorldChunkHandle : RemoteTableHandle<EventContext, WorldChunk>
        {
            protected override string RemoteTableName => "world_chunk";

            public sealed class KeyUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(WorldChunk row) => row.Key;

                public KeyUniqueIndex(WorldChunkHandle table) : base(table) { }
            }

            public readonly KeyUniqueIndex Key;

            public sealed class WorldIdIndex : BTreeIndexBase<string>
            {
                protected override string GetKey(WorldChunk row) => row.WorldId;

                public WorldIdIndex(WorldChunkHandle table) : base(table) { }
            }

            public readonly WorldIdIndex WorldId;

            internal WorldChunkHandle(DbConnection conn) : base(conn)
            {
                Key = new(this);
                WorldId = new(this);
            }

            protected override object GetPrimaryKey(WorldChunk row) => row.Key;
        }

        public readonly WorldChunkHandle WorldChunk;
    }

    public sealed class WorldChunkCols
    {
        public global::SpacetimeDB.Col<WorldChunk, string> Key { get; }
        public global::SpacetimeDB.Col<WorldChunk, string> WorldId { get; }
        public global::SpacetimeDB.Col<WorldChunk, int> Cx { get; }
        public global::SpacetimeDB.Col<WorldChunk, int> Cy { get; }
        public global::SpacetimeDB.Col<WorldChunk, int> Cz { get; }
        public global::SpacetimeDB.Col<WorldChunk, byte> TerrainSystem { get; }
        public global::SpacetimeDB.Col<WorldChunk, byte> PayloadFormat { get; }
        public global::SpacetimeDB.Col<WorldChunk, int> PayloadVersion { get; }
        public global::SpacetimeDB.Col<WorldChunk, bool> IsEmpty { get; }
        public global::SpacetimeDB.Col<WorldChunk, bool> HasSurface { get; }
        public global::SpacetimeDB.Col<WorldChunk, System.Collections.Generic.List<byte>> Payload { get; }
        public global::SpacetimeDB.Col<WorldChunk, SpacetimeDB.Timestamp> UpdatedAt { get; }

        public WorldChunkCols(string tableName)
        {
            Key = new global::SpacetimeDB.Col<WorldChunk, string>(tableName, "key");
            WorldId = new global::SpacetimeDB.Col<WorldChunk, string>(tableName, "world_id");
            Cx = new global::SpacetimeDB.Col<WorldChunk, int>(tableName, "cx");
            Cy = new global::SpacetimeDB.Col<WorldChunk, int>(tableName, "cy");
            Cz = new global::SpacetimeDB.Col<WorldChunk, int>(tableName, "cz");
            TerrainSystem = new global::SpacetimeDB.Col<WorldChunk, byte>(tableName, "terrain_system");
            PayloadFormat = new global::SpacetimeDB.Col<WorldChunk, byte>(tableName, "payload_format");
            PayloadVersion = new global::SpacetimeDB.Col<WorldChunk, int>(tableName, "payload_version");
            IsEmpty = new global::SpacetimeDB.Col<WorldChunk, bool>(tableName, "is_empty");
            HasSurface = new global::SpacetimeDB.Col<WorldChunk, bool>(tableName, "has_surface");
            Payload = new global::SpacetimeDB.Col<WorldChunk, System.Collections.Generic.List<byte>>(tableName, "payload");
            UpdatedAt = new global::SpacetimeDB.Col<WorldChunk, SpacetimeDB.Timestamp>(tableName, "updated_at");
        }
    }

    public sealed class WorldChunkIxCols
    {
        public global::SpacetimeDB.IxCol<WorldChunk, string> Key { get; }
        public global::SpacetimeDB.IxCol<WorldChunk, string> WorldId { get; }

        public WorldChunkIxCols(string tableName)
        {
            Key = new global::SpacetimeDB.IxCol<WorldChunk, string>(tableName, "key");
            WorldId = new global::SpacetimeDB.IxCol<WorldChunk, string>(tableName, "world_id");
        }
    }
}
