// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ChatMessage
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "sender")]
        public SpacetimeDB.Identity Sender;
        [DataMember(Name = "sender_name")]
        public string SenderName;
        [DataMember(Name = "text")]
        public string Text;
        [DataMember(Name = "sent_at")]
        public SpacetimeDB.Timestamp SentAt;

        public ChatMessage(
            ulong Id,
            SpacetimeDB.Identity Sender,
            string SenderName,
            string Text,
            SpacetimeDB.Timestamp SentAt
        )
        {
            this.Id = Id;
            this.Sender = Sender;
            this.SenderName = SenderName;
            this.Text = Text;
            this.SentAt = SentAt;
        }

        public ChatMessage()
        {
            this.SenderName = "";
            this.Text = "";
        }
    }
}
