// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class DensityEdit
    {
        [DataMember(Name = "key")]
        public string Key;
        [DataMember(Name = "world_id")]
        public string WorldId;
        [DataMember(Name = "x")]
        public int X;
        [DataMember(Name = "y")]
        public int Y;
        [DataMember(Name = "z")]
        public int Z;
        [DataMember(Name = "density")]
        public float Density;
        [DataMember(Name = "material")]
        public uint Material;
        [DataMember(Name = "edited_by")]
        public SpacetimeDB.Identity EditedBy;
        [DataMember(Name = "edited_at")]
        public SpacetimeDB.Timestamp EditedAt;

        public DensityEdit(
            string Key,
            string WorldId,
            int X,
            int Y,
            int Z,
            float Density,
            uint Material,
            SpacetimeDB.Identity EditedBy,
            SpacetimeDB.Timestamp EditedAt
        )
        {
            this.Key = Key;
            this.WorldId = WorldId;
            this.X = X;
            this.Y = Y;
            this.Z = Z;
            this.Density = Density;
            this.Material = Material;
            this.EditedBy = EditedBy;
            this.EditedAt = EditedAt;
        }

        public DensityEdit()
        {
            this.Key = "";
            this.WorldId = "";
        }
    }
}
