// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Player
    {
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "online")]
        public bool Online;
        [DataMember(Name = "x")]
        public float X;
        [DataMember(Name = "y")]
        public float Y;
        [DataMember(Name = "z")]
        public float Z;
        [DataMember(Name = "yaw")]
        public float Yaw;
        [DataMember(Name = "pitch")]
        public float Pitch;
        [DataMember(Name = "color_rgba")]
        public uint ColorRgba;
        [DataMember(Name = "last_seen")]
        public SpacetimeDB.Timestamp LastSeen;

        public Player(
            SpacetimeDB.Identity Identity,
            string Name,
            bool Online,
            float X,
            float Y,
            float Z,
            float Yaw,
            float Pitch,
            uint ColorRgba,
            SpacetimeDB.Timestamp LastSeen
        )
        {
            this.Identity = Identity;
            this.Name = Name;
            this.Online = Online;
            this.X = X;
            this.Y = Y;
            this.Z = Z;
            this.Yaw = Yaw;
            this.Pitch = Pitch;
            this.ColorRgba = ColorRgba;
            this.LastSeen = LastSeen;
        }

        public Player()
        {
            this.Name = "";
        }
    }
}
