// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class WorldChunk
    {
        [DataMember(Name = "key")]
        public string Key;
        [DataMember(Name = "world_id")]
        public string WorldId;
        [DataMember(Name = "cx")]
        public int Cx;
        [DataMember(Name = "cy")]
        public int Cy;
        [DataMember(Name = "cz")]
        public int Cz;
        [DataMember(Name = "terrain_system")]
        public byte TerrainSystem;
        [DataMember(Name = "payload_format")]
        public byte PayloadFormat;
        [DataMember(Name = "payload_version")]
        public int PayloadVersion;
        [DataMember(Name = "is_empty")]
        public bool IsEmpty;
        [DataMember(Name = "has_surface")]
        public bool HasSurface;
        [DataMember(Name = "payload")]
        public System.Collections.Generic.List<byte> Payload;
        [DataMember(Name = "updated_at")]
        public SpacetimeDB.Timestamp UpdatedAt;

        public WorldChunk(
            string Key,
            string WorldId,
            int Cx,
            int Cy,
            int Cz,
            byte TerrainSystem,
            byte PayloadFormat,
            int PayloadVersion,
            bool IsEmpty,
            bool HasSurface,
            System.Collections.Generic.List<byte> Payload,
            SpacetimeDB.Timestamp UpdatedAt
        )
        {
            this.Key = Key;
            this.WorldId = WorldId;
            this.Cx = Cx;
            this.Cy = Cy;
            this.Cz = Cz;
            this.TerrainSystem = TerrainSystem;
            this.PayloadFormat = PayloadFormat;
            this.PayloadVersion = PayloadVersion;
            this.IsEmpty = IsEmpty;
            this.HasSurface = HasSurface;
            this.Payload = Payload;
            this.UpdatedAt = UpdatedAt;
        }

        public WorldChunk()
        {
            this.Key = "";
            this.WorldId = "";
            this.Payload = new();
        }
    }
}
