// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class WorldState
    {
        [DataMember(Name = "world_id")]
        public string WorldId;
        [DataMember(Name = "world_seed")]
        public int WorldSeed;
        [DataMember(Name = "generator_version")]
        public uint GeneratorVersion;
        [DataMember(Name = "terrain_system")]
        public byte TerrainSystem;
        [DataMember(Name = "voxel_size")]
        public float VoxelSize;
        [DataMember(Name = "min_chunk_y")]
        public int MinChunkY;
        [DataMember(Name = "max_chunk_y")]
        public int MaxChunkY;
        [DataMember(Name = "world_min_chunk_x")]
        public int WorldMinChunkX;
        [DataMember(Name = "world_min_chunk_z")]
        public int WorldMinChunkZ;
        [DataMember(Name = "world_max_chunk_x")]
        public int WorldMaxChunkX;
        [DataMember(Name = "world_max_chunk_z")]
        public int WorldMaxChunkZ;
        [DataMember(Name = "generation_profile_id")]
        public string GenerationProfileId;
        [DataMember(Name = "generation_signature")]
        public string GenerationSignature;
        [DataMember(Name = "updated_by")]
        public SpacetimeDB.Identity UpdatedBy;
        [DataMember(Name = "updated_at")]
        public SpacetimeDB.Timestamp UpdatedAt;

        public WorldState(
            string WorldId,
            int WorldSeed,
            uint GeneratorVersion,
            byte TerrainSystem,
            float VoxelSize,
            int MinChunkY,
            int MaxChunkY,
            int WorldMinChunkX,
            int WorldMinChunkZ,
            int WorldMaxChunkX,
            int WorldMaxChunkZ,
            string GenerationProfileId,
            string GenerationSignature,
            SpacetimeDB.Identity UpdatedBy,
            SpacetimeDB.Timestamp UpdatedAt
        )
        {
            this.WorldId = WorldId;
            this.WorldSeed = WorldSeed;
            this.GeneratorVersion = GeneratorVersion;
            this.TerrainSystem = TerrainSystem;
            this.VoxelSize = VoxelSize;
            this.MinChunkY = MinChunkY;
            this.MaxChunkY = MaxChunkY;
            this.WorldMinChunkX = WorldMinChunkX;
            this.WorldMinChunkZ = WorldMinChunkZ;
            this.WorldMaxChunkX = WorldMaxChunkX;
            this.WorldMaxChunkZ = WorldMaxChunkZ;
            this.GenerationProfileId = GenerationProfileId;
            this.GenerationSignature = GenerationSignature;
            this.UpdatedBy = UpdatedBy;
            this.UpdatedAt = UpdatedAt;
        }

        public WorldState()
        {
            this.WorldId = "";
            this.GenerationProfileId = "";
            this.GenerationSignature = "";
        }
    }
}
