// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ClearWorldHandler(ReducerEventContext ctx, string worldId);
        public event ClearWorldHandler? OnClearWorld;

        public void ClearWorld(string worldId)
        {
            conn.InternalCallReducer(new Reducer.ClearWorld(worldId));
        }

        public bool InvokeClearWorld(ReducerEventContext ctx, Reducer.ClearWorld args)
        {
            if (OnClearWorld == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnClearWorld(
                ctx,
                args.WorldId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ClearWorld : Reducer, IReducerArgs
        {
            [DataMember(Name = "world_id")]
            public string WorldId;

            public ClearWorld(string WorldId)
            {
                this.WorldId = WorldId;
            }

            public ClearWorld()
            {
                this.WorldId = "";
            }

            string IReducerArgs.ReducerName => "clear_world";
        }
    }
}
