// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DeleteWorldInstanceHandler(ReducerEventContext ctx, string worldId);
        public event DeleteWorldInstanceHandler? OnDeleteWorldInstance;

        public void DeleteWorldInstance(string worldId)
        {
            conn.InternalCallReducer(new Reducer.DeleteWorldInstance(worldId));
        }

        public bool InvokeDeleteWorldInstance(ReducerEventContext ctx, Reducer.DeleteWorldInstance args)
        {
            if (OnDeleteWorldInstance == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDeleteWorldInstance(
                ctx,
                args.WorldId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DeleteWorldInstance : Reducer, IReducerArgs
        {
            [DataMember(Name = "world_id")]
            public string WorldId;

            public DeleteWorldInstance(string WorldId)
            {
                this.WorldId = WorldId;
            }

            public DeleteWorldInstance()
            {
                this.WorldId = "";
            }

            string IReducerArgs.ReducerName => "delete_world_instance";
        }
    }
}
