// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void EditDensityHandler(ReducerEventContext ctx, string worldId, System.Collections.Generic.List<int> xs, System.Collections.Generic.List<int> ys, System.Collections.Generic.List<int> zs, System.Collections.Generic.List<float> densities, System.Collections.Generic.List<uint> materials);
        public event EditDensityHandler? OnEditDensity;

        public void EditDensity(string worldId, System.Collections.Generic.List<int> xs, System.Collections.Generic.List<int> ys, System.Collections.Generic.List<int> zs, System.Collections.Generic.List<float> densities, System.Collections.Generic.List<uint> materials)
        {
            conn.InternalCallReducer(new Reducer.EditDensity(worldId, xs, ys, zs, densities, materials));
        }

        public bool InvokeEditDensity(ReducerEventContext ctx, Reducer.EditDensity args)
        {
            if (OnEditDensity == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnEditDensity(
                ctx,
                args.WorldId,
                args.Xs,
                args.Ys,
                args.Zs,
                args.Densities,
                args.Materials
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class EditDensity : Reducer, IReducerArgs
        {
            [DataMember(Name = "world_id")]
            public string WorldId;
            [DataMember(Name = "xs")]
            public System.Collections.Generic.List<int> Xs;
            [DataMember(Name = "ys")]
            public System.Collections.Generic.List<int> Ys;
            [DataMember(Name = "zs")]
            public System.Collections.Generic.List<int> Zs;
            [DataMember(Name = "densities")]
            public System.Collections.Generic.List<float> Densities;
            [DataMember(Name = "materials")]
            public System.Collections.Generic.List<uint> Materials;

            public EditDensity(
                string WorldId,
                System.Collections.Generic.List<int> Xs,
                System.Collections.Generic.List<int> Ys,
                System.Collections.Generic.List<int> Zs,
                System.Collections.Generic.List<float> Densities,
                System.Collections.Generic.List<uint> Materials
            )
            {
                this.WorldId = WorldId;
                this.Xs = Xs;
                this.Ys = Ys;
                this.Zs = Zs;
                this.Densities = Densities;
                this.Materials = Materials;
            }

            public EditDensity()
            {
                this.WorldId = "";
                this.Xs = new();
                this.Ys = new();
                this.Zs = new();
                this.Densities = new();
                this.Materials = new();
            }

            string IReducerArgs.ReducerName => "edit_density";
        }
    }
}
