// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void EditBlockHandler(ReducerEventContext ctx, string worldId, int x, int y, int z, uint material);
        public event EditBlockHandler? OnEditBlock;

        public void EditBlock(string worldId, int x, int y, int z, uint material)
        {
            conn.InternalCallReducer(new Reducer.EditBlock(worldId, x, y, z, material));
        }

        public bool InvokeEditBlock(ReducerEventContext ctx, Reducer.EditBlock args)
        {
            if (OnEditBlock == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnEditBlock(
                ctx,
                args.WorldId,
                args.X,
                args.Y,
                args.Z,
                args.Material
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class EditBlock : Reducer, IReducerArgs
        {
            [DataMember(Name = "world_id")]
            public string WorldId;
            [DataMember(Name = "x")]
            public int X;
            [DataMember(Name = "y")]
            public int Y;
            [DataMember(Name = "z")]
            public int Z;
            [DataMember(Name = "material")]
            public uint Material;

            public EditBlock(
                string WorldId,
                int X,
                int Y,
                int Z,
                uint Material
            )
            {
                this.WorldId = WorldId;
                this.X = X;
                this.Y = Y;
                this.Z = Z;
                this.Material = Material;
            }

            public EditBlock()
            {
                this.WorldId = "";
            }

            string IReducerArgs.ReducerName => "edit_block";
        }
    }
}
