// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SetPlayerNameHandler(ReducerEventContext ctx, string name);
        public event SetPlayerNameHandler? OnSetPlayerName;

        public void SetPlayerName(string name)
        {
            conn.InternalCallReducer(new Reducer.SetPlayerName(name));
        }

        public bool InvokeSetPlayerName(ReducerEventContext ctx, Reducer.SetPlayerName args)
        {
            if (OnSetPlayerName == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSetPlayerName(
                ctx,
                args.Name
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SetPlayerName : Reducer, IReducerArgs
        {
            [DataMember(Name = "name")]
            public string Name;

            public SetPlayerName(string Name)
            {
                this.Name = Name;
            }

            public SetPlayerName()
            {
                this.Name = "";
            }

            string IReducerArgs.ReducerName => "set_player_name";
        }
    }
}
