// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SetWorldStateHandler(ReducerEventContext ctx, string worldId, int worldSeed, uint generatorVersion, byte terrainSystem, float voxelSize, int minChunkY, int maxChunkY, int worldMinChunkX, int worldMinChunkZ, int worldMaxChunkX, int worldMaxChunkZ, string generationProfileId, string generationSignature);
        public event SetWorldStateHandler? OnSetWorldState;

        public void SetWorldState(string worldId, int worldSeed, uint generatorVersion, byte terrainSystem, float voxelSize, int minChunkY, int maxChunkY, int worldMinChunkX, int worldMinChunkZ, int worldMaxChunkX, int worldMaxChunkZ, string generationProfileId, string generationSignature)
        {
            conn.InternalCallReducer(new Reducer.SetWorldState(worldId, worldSeed, generatorVersion, terrainSystem, voxelSize, minChunkY, maxChunkY, worldMinChunkX, worldMinChunkZ, worldMaxChunkX, worldMaxChunkZ, generationProfileId, generationSignature));
        }

        public bool InvokeSetWorldState(ReducerEventContext ctx, Reducer.SetWorldState args)
        {
            if (OnSetWorldState == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSetWorldState(
                ctx,
                args.WorldId,
                args.WorldSeed,
                args.GeneratorVersion,
                args.TerrainSystem,
                args.VoxelSize,
                args.MinChunkY,
                args.MaxChunkY,
                args.WorldMinChunkX,
                args.WorldMinChunkZ,
                args.WorldMaxChunkX,
                args.WorldMaxChunkZ,
                args.GenerationProfileId,
                args.GenerationSignature
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SetWorldState : Reducer, IReducerArgs
        {
            [DataMember(Name = "world_id")]
            public string WorldId;
            [DataMember(Name = "world_seed")]
            public int WorldSeed;
            [DataMember(Name = "generator_version")]
            public uint GeneratorVersion;
            [DataMember(Name = "terrain_system")]
            public byte TerrainSystem;
            [DataMember(Name = "voxel_size")]
            public float VoxelSize;
            [DataMember(Name = "min_chunk_y")]
            public int MinChunkY;
            [DataMember(Name = "max_chunk_y")]
            public int MaxChunkY;
            [DataMember(Name = "world_min_chunk_x")]
            public int WorldMinChunkX;
            [DataMember(Name = "world_min_chunk_z")]
            public int WorldMinChunkZ;
            [DataMember(Name = "world_max_chunk_x")]
            public int WorldMaxChunkX;
            [DataMember(Name = "world_max_chunk_z")]
            public int WorldMaxChunkZ;
            [DataMember(Name = "generation_profile_id")]
            public string GenerationProfileId;
            [DataMember(Name = "generation_signature")]
            public string GenerationSignature;

            public SetWorldState(
                string WorldId,
                int WorldSeed,
                uint GeneratorVersion,
                byte TerrainSystem,
                float VoxelSize,
                int MinChunkY,
                int MaxChunkY,
                int WorldMinChunkX,
                int WorldMinChunkZ,
                int WorldMaxChunkX,
                int WorldMaxChunkZ,
                string GenerationProfileId,
                string GenerationSignature
            )
            {
                this.WorldId = WorldId;
                this.WorldSeed = WorldSeed;
                this.GeneratorVersion = GeneratorVersion;
                this.TerrainSystem = TerrainSystem;
                this.VoxelSize = VoxelSize;
                this.MinChunkY = MinChunkY;
                this.MaxChunkY = MaxChunkY;
                this.WorldMinChunkX = WorldMinChunkX;
                this.WorldMinChunkZ = WorldMinChunkZ;
                this.WorldMaxChunkX = WorldMaxChunkX;
                this.WorldMaxChunkZ = WorldMaxChunkZ;
                this.GenerationProfileId = GenerationProfileId;
                this.GenerationSignature = GenerationSignature;
            }

            public SetWorldState()
            {
                this.WorldId = "";
                this.GenerationProfileId = "";
                this.GenerationSignature = "";
            }

            string IReducerArgs.ReducerName => "set_world_state";
        }
    }
}
