// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpdatePlayerTransformHandler(ReducerEventContext ctx, float x, float y, float z, float yaw, float pitch);
        public event UpdatePlayerTransformHandler? OnUpdatePlayerTransform;

        public void UpdatePlayerTransform(float x, float y, float z, float yaw, float pitch)
        {
            conn.InternalCallReducer(new Reducer.UpdatePlayerTransform(x, y, z, yaw, pitch));
        }

        public bool InvokeUpdatePlayerTransform(ReducerEventContext ctx, Reducer.UpdatePlayerTransform args)
        {
            if (OnUpdatePlayerTransform == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUpdatePlayerTransform(
                ctx,
                args.X,
                args.Y,
                args.Z,
                args.Yaw,
                args.Pitch
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpdatePlayerTransform : Reducer, IReducerArgs
        {
            [DataMember(Name = "x")]
            public float X;
            [DataMember(Name = "y")]
            public float Y;
            [DataMember(Name = "z")]
            public float Z;
            [DataMember(Name = "yaw")]
            public float Yaw;
            [DataMember(Name = "pitch")]
            public float Pitch;

            public UpdatePlayerTransform(
                float X,
                float Y,
                float Z,
                float Yaw,
                float Pitch
            )
            {
                this.X = X;
                this.Y = Y;
                this.Z = Z;
                this.Yaw = Yaw;
                this.Pitch = Pitch;
            }

            public UpdatePlayerTransform()
            {
            }

            string IReducerArgs.ReducerName => "update_player_transform";
        }
    }
}
