// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UploadChunkHandler(ReducerEventContext ctx, string worldId, int cx, int cy, int cz, byte terrainSystem, byte payloadFormat, int payloadVersion, bool isEmpty, bool hasSurface, System.Collections.Generic.List<byte> payload);
        public event UploadChunkHandler? OnUploadChunk;

        public void UploadChunk(string worldId, int cx, int cy, int cz, byte terrainSystem, byte payloadFormat, int payloadVersion, bool isEmpty, bool hasSurface, System.Collections.Generic.List<byte> payload)
        {
            conn.InternalCallReducer(new Reducer.UploadChunk(worldId, cx, cy, cz, terrainSystem, payloadFormat, payloadVersion, isEmpty, hasSurface, payload));
        }

        public bool InvokeUploadChunk(ReducerEventContext ctx, Reducer.UploadChunk args)
        {
            if (OnUploadChunk == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUploadChunk(
                ctx,
                args.WorldId,
                args.Cx,
                args.Cy,
                args.Cz,
                args.TerrainSystem,
                args.PayloadFormat,
                args.PayloadVersion,
                args.IsEmpty,
                args.HasSurface,
                args.Payload
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UploadChunk : Reducer, IReducerArgs
        {
            [DataMember(Name = "world_id")]
            public string WorldId;
            [DataMember(Name = "cx")]
            public int Cx;
            [DataMember(Name = "cy")]
            public int Cy;
            [DataMember(Name = "cz")]
            public int Cz;
            [DataMember(Name = "terrain_system")]
            public byte TerrainSystem;
            [DataMember(Name = "payload_format")]
            public byte PayloadFormat;
            [DataMember(Name = "payload_version")]
            public int PayloadVersion;
            [DataMember(Name = "is_empty")]
            public bool IsEmpty;
            [DataMember(Name = "has_surface")]
            public bool HasSurface;
            [DataMember(Name = "payload")]
            public System.Collections.Generic.List<byte> Payload;

            public UploadChunk(
                string WorldId,
                int Cx,
                int Cy,
                int Cz,
                byte TerrainSystem,
                byte PayloadFormat,
                int PayloadVersion,
                bool IsEmpty,
                bool HasSurface,
                System.Collections.Generic.List<byte> Payload
            )
            {
                this.WorldId = WorldId;
                this.Cx = Cx;
                this.Cy = Cy;
                this.Cz = Cz;
                this.TerrainSystem = TerrainSystem;
                this.PayloadFormat = PayloadFormat;
                this.PayloadVersion = PayloadVersion;
                this.IsEmpty = IsEmpty;
                this.HasSurface = HasSurface;
                this.Payload = Payload;
            }

            public UploadChunk()
            {
                this.WorldId = "";
                this.Payload = new();
            }

            string IReducerArgs.ReducerName => "upload_chunk";
        }
    }
}
